# This will be the subscriber for the Trigger
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crawler-provisioner
  namespace: crawler-system
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      serviceAccountName: provisioner
      containers:
        - image: quay.io/maxgio92/cloudevents-podgateway-client-provisioner:0.1.3
          imagePullPolicy: Always
          args:
            - --client-namespace=crawler-system
            - --client-image=alpine/curl
            - --client-command="sleep"
            - --client-command="infinity"
